### ISSUE TITLE
Server crash | Workshop Mod?

### ISSUE THREAD

**Issue by xKyuu** [Steiner2/Project-Zomboid-Server#2]
hallo mister admin sir dieses server noch immer nix ich denken das bogen diese macht

**Comment by Steiner2** [comment]
Ich habe **MandelaBowAndArrow** entfernt und den Server wieder hochgefahren.

**Comment by Steiner2** [comment]
> Ich habe **MandelaBowAndArrow** entfernt und den Server wieder hochgefahren.

Ich habe gesehen, dass nach einem Update das `-servername` Argument im Startscript gefehlt hat. Jetzt wird die richtige Datenbank wieder angesprochen und der Server sollte erreichbar sein. 

Die Mod habe ich testweise wieder hinzugefügt. Bitte nochmal Feedback geben ob es weiterhin Probleme gibt.
